version: "3.3"
   
services:
  db:
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.takserver-db
    volumes:
      - "db_data:/var/lib/postgresql/data"
      # - "./tak-db-data:/var/lib/postgresql/data"
      - "./tak:/opt/tak:z"
    networks:
      tak:
        aliases:
          - tak-database
    ports:
      - 5432:5432 
    restart: always

  tak:
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.takserver-zt
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    ports:
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      # - "8443:8443"
      - "8444:8444"
      - "8446:8446"
      - "8447:8447"
      - "9000:9000"
      - "9001:9001"
      - "8080:8080"
      - "8452:8452"
    networks:
      tak:
    depends_on:
      - db
    environment:
      - ZEROTIER_JOIN_NETWORKS
    volumes:
      - "./tak:/opt/tak:z"
      # - tak-server-zt-config:/var/lib/zerotier-one
      - ./zerotier-config/:/var/lib/zerotier-one
    restart: always
  
volumes:
  db_data:

networks:
  tak:
    name: tak
    external: true
