FROM postgres:15

# this is slow - updates all packages

RUN apt-get update && \
    apt-get install -y postgresql-15-postgis-3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/bash", "-c", "/opt/tak/db-utils/configureInDocker.sh"]
