FROM openjdk:17-jdk-bullseye
RUN apt update && \
	apt-get install -y emacs-nox net-tools netcat vim && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# COPY ./tak /opt/tak

ENTRYPOINT ["/bin/bash", "-c", "/opt/tak/configureInDocker.sh init &>> /opt/tak/logs/takserver.log"]