FROM codehausau/zerotier-docker:1.12.1 as zerotier

# Use the official Node.js image as the base image
FROM openjdk:11-jdk-bullseye

COPY --from=zerotier /usr/sbin/zero* /usr/sbin/
COPY --from=zerotier /entrypoint.sh /entrypoint.sh

RUN apt update && \
	apt-get install -y emacs-nox net-tools netcat vim

COPY ./docker/amd64/run-service.sh /run-service.sh

CMD []
# ENTRYPOINT ["/entrypoint.sh"]
ENTRYPOINT ["/bin/bash", "-c", "/entrypoint.sh"]
